# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app_test.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AppTestWindow(object):
    def setupUi(self, AppTestWindow):
        AppTestWindow.setObjectName("AppTestWindow")
        AppTestWindow.resize(1600, 900)
        AppTestWindow.setStyleSheet("\n"
"QMainWindow {\n"
"    background-color: #f0f2f5;\n"
"}\n"
"QGroupBox {\n"
"    font-weight: bold;\n"
"    border: 1px solid #dcdfe6;\n"
"    border-radius: 4px;\n"
"    margin-top: 10px;\n"
"    background-color: #ffffff;\n"
"}\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top left;\n"
"    padding: 0 5px;\n"
"    left: 10px;\n"
"    color: #606266;\n"
"}\n"
"QTableWidget {\n"
"    border: none;\n"
"    gridline-color: #ebeef5;\n"
"    selection-background-color: #409eff;\n"
"}\n"
"QHeaderView::section {\n"
"    background-color: #f5f7fa;\n"
"    border: none;\n"
"    border-right: 1px solid #ebeef5;\n"
"    border-bottom: 1px solid #ebeef5;\n"
"    height: 30px;\n"
"    color: #909399;\n"
"}\n"
"/* 通用按钮样式 (会被下方特定ID覆盖) */\n"
"QPushButton {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #dcdfe6;\n"
"    border-radius: 4px;\n"
"    padding: 5px 15px;\n"
"    color: #606266;\n"
"}\n"
"QPushButton:hover {\n"
"    color: #409eff;\n"
"    border-color: #c6e2ff;\n"
"    background-color: #ecf5ff;\n"
"}\n"
"QTextEdit {\n"
"    border: 1px solid #dcdfe6;\n"
"    border-radius: 4px;\n"
"    background-color: #fafafa;\n"
"    font-family: \"Consolas\", \"Courier New\", monospace;\n"
"}\n"
"\n"
"/* ================= 底部面板新样式 (New Pro Style) ================= */\n"
"\n"
"/* 底部容器背景 */\n"
"#bottom_panel {\n"
"    background-color: #ffffff;\n"
"    border-top: 1px solid #e4e7ed;\n"
"}\n"
"\n"
"/* --- 控制按钮区域 --- */\n"
"/* 主开始按钮 - Hero Button */\n"
"#start_btn {\n"
"    background-color: #409eff;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 6px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    padding: 8px 20px;\n"
"}\n"
"#start_btn:hover {\n"
"    background-color: #66b1ff;\n"
"}\n"
"#start_btn:pressed {\n"
"    background-color: #3a8ee6;\n"
"}\n"
"\n"
"/* 停止按钮 - 危险色 */\n"
"#stop_btn {\n"
"    background-color: #fef0f0;\n"
"    color: #f56c6c;\n"
"    border: 1px solid #fbc4c4;\n"
"    border-radius: 6px;\n"
"}\n"
"#stop_btn:hover {\n"
"    background-color: #f56c6c;\n"
"    color: white;\n"
"}\n"
"\n"
"/* 暂停按钮 */\n"
"#pause_btn {\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"/* --- 进度条区域 --- */\n"
"QProgressBar {\n"
"    border: 1px solid #c0c4cc;\n"
"    background-color: #ffffff;\n"
"    border-radius: 4px;\n"
"    text-align: center;\n"
"    color: #303133;\n"
"    font-family: Arial;\n"
"    font-size: 13px;\n"
"}\n"
"QProgressBar::chunk {\n"
"    background-color: #9ec6fc;\n"
"    border-radius: 3px;\n"
"    margin: 1px;\n"
"}\n"
"/* 状态文字 */\n"
"#label_status {\n"
"    color: #909399;\n"
"    font-size: 12px;\n"
"}\n"
"#label_percent {\n"
"    color: #409eff;\n"
"    font-weight: bold;\n"
"    font-family: Arial;\n"
"}\n"
"\n"
"/* --- 结果仪表盘区域 (KPI Cards) --- */\n"
"/* 数字大字体 */\n"
".stat_number {\n"
"    font-family: \"Segoe UI\", Arial, sans-serif;\n"
"    font-size: 26px;\n"
"    font-weight: bold;\n"
"    background: transparent;\n"
"}\n"
"/* 标签小字体 */\n"
".stat_label {\n"
"    font-size: 12px;\n"
"    color: #909399;\n"
"    font-weight: bold;\n"
"}\n"
"/* 颜色定义 */\n"
"#stat_num_total { color: #303133; }\n"
"#stat_num_pass { color: #67c23a; }\n"
"#stat_num_fail { color: #f56c6c; }\n"
"#stat_num_skip { color: #e6a23c; } /* 新增跳过颜色 */\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(AppTestWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.main_layout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.main_layout.setContentsMargins(15, 15, 15, 0)
        self.main_layout.setSpacing(0)
        self.main_layout.setObjectName("main_layout")
        self.top_horizontalLayout = QtWidgets.QHBoxLayout()
        self.top_horizontalLayout.setSpacing(12)
        self.top_horizontalLayout.setObjectName("top_horizontalLayout")
        self.group_case = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.group_case.sizePolicy().hasHeightForWidth())
        self.group_case.setSizePolicy(sizePolicy)
        self.group_case.setObjectName("group_case")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.group_case)
        self.verticalLayout_2.setProperty("contentsMargins", QtCore.QRect(10, 10, 0, 0))
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.case_table = QtWidgets.QTableWidget(self.group_case)
        self.case_table.setAlternatingRowColors(True)
        self.case_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.case_table.setObjectName("case_table")
        self.case_table.setColumnCount(3)
        self.case_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.case_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.case_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.case_table.setHorizontalHeaderItem(2, item)
        self.case_table.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_2.addWidget(self.case_table)
        self.top_horizontalLayout.addWidget(self.group_case)
        self.group_log = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.group_log.sizePolicy().hasHeightForWidth())
        self.group_log.setSizePolicy(sizePolicy)
        self.group_log.setObjectName("group_log")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.group_log)
        self.verticalLayout_3.setProperty("contentsMargins", QtCore.QRect(10, 10, 0, 0))
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.log_text = QtWidgets.QTextEdit(self.group_log)
        self.log_text.setReadOnly(True)
        self.log_text.setObjectName("log_text")
        self.verticalLayout_3.addWidget(self.log_text)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.chk_auto_scroll = QtWidgets.QCheckBox(self.group_log)
        self.chk_auto_scroll.setChecked(True)
        self.chk_auto_scroll.setObjectName("chk_auto_scroll")
        self.horizontalLayout_2.addWidget(self.chk_auto_scroll)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.copy_btn = QtWidgets.QPushButton(self.group_log)
        icon = QtGui.QIcon.fromTheme("edit-copy")
        self.copy_btn.setIcon(icon)
        self.copy_btn.setObjectName("copy_btn")
        self.horizontalLayout_2.addWidget(self.copy_btn)
        self.save_btn = QtWidgets.QPushButton(self.group_log)
        icon = QtGui.QIcon.fromTheme("document-save")
        self.save_btn.setIcon(icon)
        self.save_btn.setObjectName("save_btn")
        self.horizontalLayout_2.addWidget(self.save_btn)
        self.clear_btn = QtWidgets.QPushButton(self.group_log)
        icon = QtGui.QIcon.fromTheme("edit-clear")
        self.clear_btn.setIcon(icon)
        self.clear_btn.setObjectName("clear_btn")
        self.horizontalLayout_2.addWidget(self.clear_btn)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.top_horizontalLayout.addWidget(self.group_log)
        self.group_config = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.group_config.sizePolicy().hasHeightForWidth())
        self.group_config.setSizePolicy(sizePolicy)
        self.group_config.setObjectName("group_config")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.group_config)
        self.verticalLayout_4.setProperty("contentsMargins", QtCore.QRect(10, 10, 0, 0))
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setVerticalSpacing(15)
        self.formLayout.setObjectName("formLayout")
        self.label_device = QtWidgets.QLabel(self.group_config)
        self.label_device.setObjectName("label_device")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_device)
        self.device_combo = QtWidgets.QComboBox(self.group_config)
        self.device_combo.setObjectName("device_combo")
        self.device_combo.addItem("")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.device_combo)
        self.label_interval = QtWidgets.QLabel(self.group_config)
        self.label_interval.setObjectName("label_interval")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_interval)
        self.interval_combo = QtWidgets.QComboBox(self.group_config)
        self.interval_combo.setObjectName("interval_combo")
        self.interval_combo.addItem("")
        self.interval_combo.addItem("")
        self.interval_combo.addItem("")
        self.interval_combo.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.interval_combo)
        self.label_count = QtWidgets.QLabel(self.group_config)
        self.label_count.setObjectName("label_count")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_count)
        self.count_combo = QtWidgets.QComboBox(self.group_config)
        self.count_combo.setObjectName("count_combo")
        self.count_combo.addItem("")
        self.count_combo.addItem("")
        self.count_combo.addItem("")
        self.count_combo.addItem("")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.count_combo)
        self.label_type = QtWidgets.QLabel(self.group_config)
        self.label_type.setObjectName("label_type")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_type)
        self.test_type_combo = QtWidgets.QComboBox(self.group_config)
        self.test_type_combo.setObjectName("test_type_combo")
        self.test_type_combo.addItem("")
        self.test_type_combo.addItem("")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.test_type_combo)
        self.verticalLayout_4.addLayout(self.formLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.top_horizontalLayout.addWidget(self.group_config)
        self.top_horizontalLayout.setStretch(0, 5)
        self.top_horizontalLayout.setStretch(1, 3)
        self.top_horizontalLayout.setStretch(2, 2)
        self.main_layout.addLayout(self.top_horizontalLayout)
        self.bottom_panel = QtWidgets.QFrame(self.centralwidget)
        self.bottom_panel.setMinimumSize(QtCore.QSize(0, 110))
        self.bottom_panel.setMaximumSize(QtCore.QSize(16777215, 110))
        self.bottom_panel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.bottom_panel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bottom_panel.setObjectName("bottom_panel")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.bottom_panel)
        self.horizontalLayout_3.setContentsMargins(20, 15, 20, 15)
        self.horizontalLayout_3.setSpacing(25)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.layout_controls = QtWidgets.QHBoxLayout()
        self.layout_controls.setSpacing(15)
        self.layout_controls.setObjectName("layout_controls")
        self.start_btn = QtWidgets.QPushButton(self.bottom_panel)
        self.start_btn.setMinimumSize(QtCore.QSize(130, 45))
        self.start_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon = QtGui.QIcon.fromTheme("media-playback-start")
        self.start_btn.setIcon(icon)
        self.start_btn.setIconSize(QtCore.QSize(20, 20))
        self.start_btn.setObjectName("start_btn")
        self.layout_controls.addWidget(self.start_btn)
        self.layout_mini_btns = QtWidgets.QVBoxLayout()
        self.layout_mini_btns.setSpacing(5)
        self.layout_mini_btns.setObjectName("layout_mini_btns")
        self.pause_btn = QtWidgets.QPushButton(self.bottom_panel)
        self.pause_btn.setMinimumSize(QtCore.QSize(80, 0))
        self.pause_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon = QtGui.QIcon.fromTheme("media-playback-pause")
        self.pause_btn.setIcon(icon)
        self.pause_btn.setObjectName("pause_btn")
        self.layout_mini_btns.addWidget(self.pause_btn)
        self.stop_btn = QtWidgets.QPushButton(self.bottom_panel)
        self.stop_btn.setMinimumSize(QtCore.QSize(80, 0))
        self.stop_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon = QtGui.QIcon.fromTheme("media-playback-stop")
        self.stop_btn.setIcon(icon)
        self.stop_btn.setObjectName("stop_btn")
        self.layout_mini_btns.addWidget(self.stop_btn)
        self.layout_controls.addLayout(self.layout_mini_btns)
        self.horizontalLayout_3.addLayout(self.layout_controls)
        self.line_sep_1 = QtWidgets.QFrame(self.bottom_panel)
        self.line_sep_1.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_sep_1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_sep_1.setObjectName("line_sep_1")
        self.horizontalLayout_3.addWidget(self.line_sep_1)
        self.layout_progress = QtWidgets.QVBoxLayout()
        self.layout_progress.setSpacing(6)
        self.layout_progress.setObjectName("layout_progress")
        self.layout_prog_text = QtWidgets.QHBoxLayout()
        self.layout_prog_text.setObjectName("layout_prog_text")
        self.label_status = QtWidgets.QLabel(self.bottom_panel)
        self.label_status.setObjectName("label_status")
        self.layout_prog_text.addWidget(self.label_status)
        self.label_percent = QtWidgets.QLabel(self.bottom_panel)
        self.label_percent.setText("")
        self.label_percent.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_percent.setObjectName("label_percent")
        self.layout_prog_text.addWidget(self.label_percent)
        self.layout_progress.addLayout(self.layout_prog_text)
        self.progressBar = QtWidgets.QProgressBar(self.bottom_panel)
        self.progressBar.setMinimumSize(QtCore.QSize(0, 26))
        self.progressBar.setMaximumSize(QtCore.QSize(16777215, 26))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(True)
        self.progressBar.setObjectName("progressBar")
        self.layout_progress.addWidget(self.progressBar)
        self.horizontalLayout_3.addLayout(self.layout_progress)
        self.line_sep_2 = QtWidgets.QFrame(self.bottom_panel)
        self.line_sep_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_sep_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_sep_2.setObjectName("line_sep_2")
        self.horizontalLayout_3.addWidget(self.line_sep_2)
        self.layout_dashboard = QtWidgets.QHBoxLayout()
        self.layout_dashboard.setSpacing(25)
        self.layout_dashboard.setObjectName("layout_dashboard")
        self.box_total = QtWidgets.QVBoxLayout()
        self.box_total.setSpacing(0)
        self.box_total.setObjectName("box_total")
        self.stat_num_total = QtWidgets.QLabel(self.bottom_panel)
        self.stat_num_total.setAlignment(QtCore.Qt.AlignCenter)
        self.stat_num_total.setObjectName("stat_num_total")
        self.box_total.addWidget(self.stat_num_total)
        self.stat_lbl_total = QtWidgets.QLabel(self.bottom_panel)
        self.stat_lbl_total.setAlignment(QtCore.Qt.AlignCenter)
        self.stat_lbl_total.setObjectName("stat_lbl_total")
        self.box_total.addWidget(self.stat_lbl_total)
        self.layout_dashboard.addLayout(self.box_total)
        self.box_pass = QtWidgets.QVBoxLayout()
        self.box_pass.setSpacing(0)
        self.box_pass.setObjectName("box_pass")
        self.stat_num_pass = QtWidgets.QLabel(self.bottom_panel)
        self.stat_num_pass.setAlignment(QtCore.Qt.AlignCenter)
        self.stat_num_pass.setObjectName("stat_num_pass")
        self.box_pass.addWidget(self.stat_num_pass)
        self.stat_lbl_pass = QtWidgets.QLabel(self.bottom_panel)
        self.stat_lbl_pass.setAlignment(QtCore.Qt.AlignCenter)
        self.stat_lbl_pass.setObjectName("stat_lbl_pass")
        self.box_pass.addWidget(self.stat_lbl_pass)
        self.layout_dashboard.addLayout(self.box_pass)
        self.box_fail = QtWidgets.QVBoxLayout()
        self.box_fail.setSpacing(0)
        self.box_fail.setObjectName("box_fail")
        self.stat_num_fail = QtWidgets.QLabel(self.bottom_panel)
        self.stat_num_fail.setAlignment(QtCore.Qt.AlignCenter)
        self.stat_num_fail.setObjectName("stat_num_fail")
        self.box_fail.addWidget(self.stat_num_fail)
        self.stat_lbl_fail = QtWidgets.QLabel(self.bottom_panel)
        self.stat_lbl_fail.setAlignment(QtCore.Qt.AlignCenter)
        self.stat_lbl_fail.setObjectName("stat_lbl_fail")
        self.box_fail.addWidget(self.stat_lbl_fail)
        self.layout_dashboard.addLayout(self.box_fail)
        self.box_skip = QtWidgets.QVBoxLayout()
        self.box_skip.setSpacing(0)
        self.box_skip.setObjectName("box_skip")
        self.stat_num_skip = QtWidgets.QLabel(self.bottom_panel)
        self.stat_num_skip.setAlignment(QtCore.Qt.AlignCenter)
        self.stat_num_skip.setObjectName("stat_num_skip")
        self.box_skip.addWidget(self.stat_num_skip)
        self.stat_lbl_skip = QtWidgets.QLabel(self.bottom_panel)
        self.stat_lbl_skip.setAlignment(QtCore.Qt.AlignCenter)
        self.stat_lbl_skip.setObjectName("stat_lbl_skip")
        self.box_skip.addWidget(self.stat_lbl_skip)
        self.layout_dashboard.addLayout(self.box_skip)
        self.horizontalLayout_3.addLayout(self.layout_dashboard)
        self.main_layout.addWidget(self.bottom_panel)
        AppTestWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(AppTestWindow)
        self.statusbar.setObjectName("statusbar")
        AppTestWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(AppTestWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuConfig = QtWidgets.QMenu(self.menubar)
        self.menuConfig.setObjectName("menuConfig")
        self.menuOptions = QtWidgets.QMenu(self.menubar)
        self.menuOptions.setObjectName("menuOptions")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        AppTestWindow.setMenuBar(self.menubar)
        self.actionLoadScript = QtWidgets.QAction(AppTestWindow)
        icon = QtGui.QIcon.fromTheme("document-open")
        self.actionLoadScript.setIcon(icon)
        self.actionLoadScript.setObjectName("actionLoadScript")
        self.actionExportReport = QtWidgets.QAction(AppTestWindow)
        icon = QtGui.QIcon.fromTheme("document-save")
        self.actionExportReport.setIcon(icon)
        self.actionExportReport.setObjectName("actionExportReport")
        self.actionExit = QtWidgets.QAction(AppTestWindow)
        icon = QtGui.QIcon.fromTheme("application-exit")
        self.actionExit.setIcon(icon)
        self.actionExit.setObjectName("actionExit")
        self.open_config = QtWidgets.QAction(AppTestWindow)
        self.open_config.setObjectName("open_config")
        self.actionTheme = QtWidgets.QAction(AppTestWindow)
        icon = QtGui.QIcon.fromTheme("preferences-desktop-theme")
        self.actionTheme.setIcon(icon)
        self.actionTheme.setObjectName("actionTheme")
        self.actionAbout = QtWidgets.QAction(AppTestWindow)
        icon = QtGui.QIcon.fromTheme("help-about")
        self.actionAbout.setIcon(icon)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionLoadScript)
        self.menuFile.addAction(self.actionExportReport)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuConfig.addAction(self.open_config)
        self.menuOptions.addAction(self.actionTheme)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuConfig.menuAction())
        self.menubar.addAction(self.menuOptions.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(AppTestWindow)
        QtCore.QMetaObject.connectSlotsByName(AppTestWindow)

    def retranslateUi(self, AppTestWindow):
        _translate = QtCore.QCoreApplication.translate
        AppTestWindow.setWindowTitle(_translate("AppTestWindow", "APP应用自动化测试"))
        self.group_case.setTitle(_translate("AppTestWindow", "测试任务队列 (Test Cases)"))
        item = self.case_table.horizontalHeaderItem(0)
        item.setText(_translate("AppTestWindow", "ID"))
        item = self.case_table.horizontalHeaderItem(1)
        item.setText(_translate("AppTestWindow", "用例名称"))
        item = self.case_table.horizontalHeaderItem(2)
        item.setText(_translate("AppTestWindow", "状态"))
        self.group_log.setTitle(_translate("AppTestWindow", "实时执行日志 (Runtime Log)"))
        self.log_text.setHtml(_translate("AppTestWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Consolas\',\'Courier New\',\'monospace\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas\'; color:#888888;\">[System] 等待任务启动...</span></p></body></html>"))
        self.chk_auto_scroll.setText(_translate("AppTestWindow", "自动滚动"))
        self.copy_btn.setText(_translate("AppTestWindow", "复制"))
        self.save_btn.setText(_translate("AppTestWindow", "保存"))
        self.clear_btn.setText(_translate("AppTestWindow", "清空"))
        self.group_config.setTitle(_translate("AppTestWindow", "配置面板 (Settings)"))
        self.label_device.setText(_translate("AppTestWindow", "目标设备:"))
        self.device_combo.setItemText(0, _translate("AppTestWindow", "Android Emulator (Default)"))
        self.label_interval.setText(_translate("AppTestWindow", "操作间隔(s):"))
        self.interval_combo.setItemText(0, _translate("AppTestWindow", "2s"))
        self.interval_combo.setItemText(1, _translate("AppTestWindow", "5s"))
        self.interval_combo.setItemText(2, _translate("AppTestWindow", "10s"))
        self.interval_combo.setItemText(3, _translate("AppTestWindow", "15s"))
        self.label_count.setText(_translate("AppTestWindow", "循环次数:"))
        self.count_combo.setItemText(0, _translate("AppTestWindow", "1次"))
        self.count_combo.setItemText(1, _translate("AppTestWindow", "10次"))
        self.count_combo.setItemText(2, _translate("AppTestWindow", "30次"))
        self.count_combo.setItemText(3, _translate("AppTestWindow", "50次"))
        self.label_type.setText(_translate("AppTestWindow", "测试策略:"))
        self.test_type_combo.setItemText(0, _translate("AppTestWindow", "标准功能测试"))
        self.test_type_combo.setItemText(1, _translate("AppTestWindow", "Monkey 压力测试"))
        self.start_btn.setText(_translate("AppTestWindow", " 开始测试"))
        self.pause_btn.setText(_translate("AppTestWindow", "暂停"))
        self.stop_btn.setText(_translate("AppTestWindow", "停止"))
        self.label_status.setText(_translate("AppTestWindow", "等待指令..."))
        self.stat_num_total.setProperty("class", _translate("AppTestWindow", "stat_number"))
        self.stat_num_total.setText(_translate("AppTestWindow", "0"))
        self.stat_lbl_total.setProperty("class", _translate("AppTestWindow", "stat_label"))
        self.stat_lbl_total.setText(_translate("AppTestWindow", "TOTAL"))
        self.stat_num_pass.setProperty("class", _translate("AppTestWindow", "stat_number"))
        self.stat_num_pass.setText(_translate("AppTestWindow", "0"))
        self.stat_lbl_pass.setProperty("class", _translate("AppTestWindow", "stat_label"))
        self.stat_lbl_pass.setText(_translate("AppTestWindow", "PASS"))
        self.stat_num_fail.setProperty("class", _translate("AppTestWindow", "stat_number"))
        self.stat_num_fail.setText(_translate("AppTestWindow", "0"))
        self.stat_lbl_fail.setProperty("class", _translate("AppTestWindow", "stat_label"))
        self.stat_lbl_fail.setText(_translate("AppTestWindow", "FAIL"))
        self.stat_num_skip.setProperty("class", _translate("AppTestWindow", "stat_number"))
        self.stat_num_skip.setText(_translate("AppTestWindow", "0"))
        self.stat_lbl_skip.setProperty("class", _translate("AppTestWindow", "stat_label"))
        self.stat_lbl_skip.setText(_translate("AppTestWindow", "SKIP"))
        self.menuFile.setTitle(_translate("AppTestWindow", "文件(File)"))
        self.menuConfig.setTitle(_translate("AppTestWindow", "配置(Settings)"))
        self.menuOptions.setTitle(_translate("AppTestWindow", "选项(Options)"))
        self.menuHelp.setTitle(_translate("AppTestWindow", "帮助(Help)"))
        self.actionLoadScript.setText(_translate("AppTestWindow", "加载脚本"))
        self.actionExportReport.setText(_translate("AppTestWindow", "导出报告"))
        self.actionExit.setText(_translate("AppTestWindow", "退出"))
        self.open_config.setText(_translate("AppTestWindow", "配置文件"))
        self.actionTheme.setText(_translate("AppTestWindow", "切换主题"))
        self.actionAbout.setText(_translate("AppTestWindow", "关于"))
